### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by rvandewater** [hoon9405/GenHPF#17]
Hi,

With the latest adjustments I get the below error while training.
```
[2025-11-29 18:05:48,165][genhpf.utils.utils][INFO] - ***********************CUDA enviroments for all 1 workers***********************               
[2025-11-29 18:05:48,165][genhpf.train][INFO] - training on 1 devices (GPUs)                                                                         
[2025-11-29 18:05:48,165][genhpf.train][INFO] - batch size per device = 16                                                                           
epoch 001:   0%|                                                                                                            | 0/1426 [00:00<?, ?it/s]
[2025-11-29 18:05:48,225][genhpf.train][INFO] - begin training epoch 1                                                                               
[2025-11-29 18:05:48,225][genhpf.train][INFO] - Start iterating over samples                                                                         
epoch 001:  37%|█  | 521/1426 [02:47<04:46,  3.16it/s, loss=0.138, accuracy=0.98125, ups=3.16, num_updates=520, train_wall=3, gb_free=20.8, wall=168]
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [8,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [9,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [11,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [12,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [13,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [14,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [15,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [16,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [17,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [18,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [19,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [20,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [21,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [22,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [23,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [24,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [25,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [26,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [27,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [28,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [8,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [9,0,0] Assertion `srcIndex < srcSelectDimSize` 
failed.                                                                                                                                              
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [11,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [12,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [13,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [14,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [15,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [16,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [17,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [18,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [32,0,0], thread: [19,0,0] Assertion `srcIndex <                                                                                                                
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [35,0,0] Assertion `srcIndex 18:08:41 [128/1922]
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [36,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [37,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [38,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                  
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [39,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                  
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [40,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [41,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                  
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [42,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                  
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [43,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [44,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                  
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [45,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [46,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [47,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [48,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                  
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [49,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [50,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                  
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [51,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                  
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [52,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [53,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                         
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [54,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [55,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [56,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [57,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [58,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [59,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [60,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [61,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                  
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [31,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize`
 failed.                                                                                                                                             
Error executing job with overrides: ['dataset.data=/sc/home/robin.vandewater/datasets/meds/NWICU/models/abnormal_lab/blood_chemistry/hyperkalemia/fir
st_24h/genhpf/data', 'checkpoint.save_dir=/sc/home/robin.vandewater/datasets/meds/NWICU/models/abnormal_lab/blood_chemistry/hyperkalemia/first_24h/ge
nhpf/checkpoints', 'common.debug=False']                                                                                                             
Traceback (most recent call last):                                        
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/genhpf/scripts/train.py", line 349, in hydra_main                  
    distributed_utils.call_main(cfg, main)                                
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/genhpf/utils/distributed_utils.py", line 203, in call_main         
    main(cfg, **kwargs)                                                                                                                              
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/genhpf/scripts/train.py", line 114, in main                        
    valid_losses, should_stop = train(cfg, trainer, datasets, i)          
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                     
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/contextlib.py", line 81, in inner                                                
    return func(*args, **kwds)                                                                                                                       
           ^^^^^^^^^^^^^^^^^^^                                                                                                                       
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/genhpf/scripts/train.py", line 185, in train                       
    log_output = trainer.train_step(sample)                               
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                          
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/contextlib.py", line 81, in inner                                                
    return func(*args, **kwds)                                                                                                                       
           ^^^^^^^^^^^^^^^^^^^                                                                                                                       
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/genhpf/trainer.py", line 243, in train_step                        
    loss, sample_size, logging_output = self.criterion(self.model, sample)                                                                           
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                           
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl      
    return self._call_impl(*args, **kwargs)                                                                                                          
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                          
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl              
    return forward_call(*args, **kwargs)                                  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                             
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/genhpf/criterions/criterion.py", line 60, in forward               
    net_output = model(**sample["net_input"])                                                                                                        
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                        
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl      
    return self._call_impl(*args, **kwargs)                               
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                          
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl              
    return forward_call(*args, **kwargs)                                                                                                             
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                             
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/genhpf/models/genhpf_predictor.py", line 56, in forward            
    x, padding_mask = super().forward(                                    
                      ^^^^^^^^^^^^^^^^                                                                                                               
  File "/sc/home/robin.vandewater/conda3/envs/genhpf/lib/python3.11/site-packages/genhpf/models/genhpf.py", line 221, in forward                     
    if padding_mask.any():                                                                                                                           
RuntimeError: CUDA error: device-side assert triggered                                                                                               
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.                              
For debugging consider passing CUDA_LAUNCH_BLOCKING=1                     
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.   
```

**Comment by rvandewater** [comment]
[held_out.tsv](https://github.com/user-attachments/files/23835012/held_out.tsv)

**Comment by rvandewater** [comment]
[train.tsv](https://github.com/user-attachments/files/23835014/train.tsv)

**Comment by rvandewater** [comment]
Might have to do with this line that  I added to prevent preprocessing from crashing https://github.com/rvandewater/GenHPF/blob/0c094680156fef013baa453a22a37958b81fd9c3/src/genhpf/scripts/preprocess/preprocess_meds.py#L606.

**Comment by Jwoo5** [comment]
Hi, I found that this error comes from the `dpe_ids` in the preprocessed data. Specifically, I assumed that the digits that appeared in the dataset do not exceed 9,999,999,999, which will be assigned the dpe ids as [15, 14, 13, ..., 6] for each digit place. Accordingly, I set the size of the embedding layer for this type of ids to be exactly "16", which results in error when encountering the dpe id >= 16.
It turns out that some of the events in NWICU includes a value of "75,555,555,555", which I think is likely to be an error.

To handle this case, I increased the size of the embedding layer for digit place embedding to be 128 for now, and confirmed that the training runs well without errors (I hope there will be no values with >128 digits in any cases). Please see 07c2068baf771db44f3cabde4a8372c8b80a00c3, and let me know if the error was resolved from your end.

Still, I am not sure if the line that you added to the preprocessing script above will cause an error or not. It would be great if you test it as well, and make a PR regarding this.
